esphome: # Configuration de l'ESP
  name: esp_multi_relais_entites_exterieur_V5 # Nom de l'appareil
  platform: ESP8266 # Plateforme de votre esp
  board: nodemcuv2 # Type de carte, ici un NodeMCU v2

wifi: # Configuration du WiFi sur lequel l'esp se connectera
  ssid: "NomDuReseauWiFi" # Remplacer par le nom de votre réseau WiFi
  password: "MotDePasseWiFi" # Remplacer par le mot de passe de votre réseau WiFi

# Déclaration des entités
# Etant donnée que nous avons 4 entités, nous n'avons que 14 possibilités entre les relais position ON et OFF
binary_sensor: 
  - platform: gpio # Type de la plateforme
    pin: GPIO_NUM_1 # Numéro de la broche GPIO
    name: "Entite1" # Nom de l'entité
  - platform: gpio
    pin: GPIO_NUM_2
    name: "Entite2"
  - platform: gpio
    pin: GPIO_NUM_3
    name: "Entite3"
  - platform: gpio
    pin: GPIO_NUM_4
    name: "Entite4"

# Déclaration des relais
switch: 
  - platform: gpio # Type de la plateforme
    pin: GPIO_NUM_4 # Numéro de la broche GPIO
    name: "Relais1" # Nom du relais
  - platform: gpio
    pin: GPIO_NUM_5
    name: "Relais2"
  - platform: gpio
    pin: GPIO_NUM_6
    name: "Relais3"
  - platform: gpio
    pin: GPIO_NUM_7
    name: "Relais4"
  - platform: gpio
    pin: GPIO_NUM_8
    name: "Relais5"

# Automatisation pour allumer ou éteindre les relais en fonction des états des entités
automation:
  - alias: "Contrôle des relais" # Nom de l'automatisation
    trigger: # Déclencheurs de l'automatisation
      - platform: state # Type de déclencheur
        entity_id: binary_sensor.entite1 # Entité déclencheur
      - platform: state
        entity_id: binary_sensor.entite2
      - platform: state
        entity_id: binary_sensor.entite3
      - platform: state
        entity_id: binary_sensor.entite4
    action: # Actions de l'automatisation
      - choose: # Choix des actions à effectuer

      # Eteindre les relais si l'ensemble des états des entités est OFF

          - conditions: # Entite1 OFF, Entite2 OFF, Entite3 OFF, Entite4 OFF
              - condition: state # Condition sur l'état de l'entité
                entity_id: binary_sensor.entite1 # Entité concernée
                state: "off" # Etat de l'entité
              - condition: state
                entity_id: binary_sensor.entite2
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite4
                state: "off"
            sequence: # Séquence d'actions à effectuer
              - switch.turn_off: # Action à effectuer
                  - relay1
                  - relay2
                  - relay3
                  - relay4
                  - relay5
              

      # Allumer les relais si l'ensemble des états des entités est ON

          - conditions: # Entite1 ON, Entite2 ON, Entite3 ON, Entite4 ON
              - condition: state
                entity_id: binary_sensor.entite1
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite4
                state: "on"
            sequence:
              - switch.turn_on:
                  - relay1
                  - relay2
                  - relay3
                  - relay4
                  - relay5
         

      # Allumer ou éteindre relay1, relay2, relay3, relay4 et relay5 en fonction des états des entités

          - conditions: # Entite1 ON, Entite2 ON, Entite3 ON, Entite4 OFF
              - condition: state
                entity_id: binary_sensor.entite1
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite4
                state: "off"
            sequence:
              - switch.turn_on:
                  - relay1
                  - relay2
                  - relay3
                  - relay4
              - switch.turn_off:
                  - relay5
          - conditions: # Entite1 ON, Entite2 ON, Entite3 OFF, Entite4 OFF
              - condition: state
                entity_id: binary_sensor.entite1
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite4
                state: "off"
            sequence:
              - switch.turn_on:
                  - relay1
                  - relay2
                  - relay3
              - switch.turn_off:
                  - relay4
                  - relay5
          - conditions: # Entite1 ON, Entite2 ON, Entite3 OFF, Entite4 ON
              - condition: state
                entity_id: binary_sensor.entite1
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite4
                state: "on"
            sequence:
              - switch.turn_on:
                  - relay1
                  - relay2
              - switch.turn_off:
                  - relay3
                  - relay4
                  - relay5
          - conditions: # Entite1 ON, Entite2 OFF, Entite3 ON, Entite4 ON
              - condition: state
                entity_id: binary_sensor.entite1
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite4
                state: "on"
            sequence:
              - switch.turn_on:
                  - relay1
              - switch.turn_off:
                  - relay2
                  - relay3
                  - relay4
                  - relay5
          - conditions: # Entite1 ON, Entite2 OFF, Entite3 OFF, Entite4 ON
              - condition: state
                entity_id: binary_sensor.entite1
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite4
                state: "on"
            sequence:
              - switch.turn_on:
                  - relay1
                  - relay3
              - switch.turn_off:
                  - relay2
                  - relay4
                  - relay5
          - conditions: # Entite1 ON, Entite2 OFF, Entite3 ON, Entite4 OFF
              - condition: state
                entity_id: binary_sensor.entite1
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite4
                state: "off"
            sequence:
              - switch.turn_on:
                  - relay1
                  - relay3
                  - relay4
              - switch.turn_off:
                  - relay2
                  - relay5
          - conditions: # Entite1 OFF, Entite2 ON, Entite3 ON, Entite4 OFF
              - condition: state
                entity_id: binary_sensor.entite1
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite4
                state: "off"
            sequence:
              - switch.turn_on:
                  - relay1
                  - relay3
                  - relay4
                  - relay5
              - switch.turn_off:
                  - relay2
          - conditions: # Entite1 OFF, Entite2 ON, Entite3 OFF, Entite4 OFF
              - condition: state
                entity_id: binary_sensor.entite1
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite4
                state: "off"
            sequence:
              - switch.turn_on:
                  - relay2
              - switch.turn_off:
                  - relay1
                  - relay3
                  - relay4
                  - relay5
          - conditions: # Entite1 OFF, Entite2 ON, Entite3 OFF, Entite4 ON
              - condition: state
                entity_id: binary_sensor.entite1
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite4
                state: "on"
            sequence:
              - switch.turn_on:
                  - relay2
                  - relay3
              - switch.turn_off:
                  - relay1
                  - relay4
                  - relay5
          - conditions: # Entite1 OFF, Entite2 OFF, Entite3 ON, Entite4 ON
              - condition: state
                entity_id: binary_sensor.entite1
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite4
                state: "on"
            sequence:
              - switch.turn_on:
                  - relay2
                  - relay3
                  - relay4
              - switch.turn_off:
                  - relay1
                  - relay5
          - conditions: # Entite1 OFF, Entite2 OFF, Entite3 OFF, Entite4 ON
              - condition: state
                entity_id: binary_sensor.entite1
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite4
                state: "on"
            sequence:
              - switch.turn_on:
                  - relay2
                  - relay3
                  - relay4
                  - relay5
              - switch.turn_off:
                  - relay1
          - conditions: # Entite1 OFF, Entite2 OFF, Entite3 ON, Entite4 OFF
              - condition: state
                entity_id: binary_sensor.entite1
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite4
                state: "off"
            sequence:
              - switch.turn_on:
                  - relay3
              - switch.turn_off:
                  - relay1
                  - relay2
                  - relay4
                  - relay5
          
          