esphome:
  name: esp_multi_relais_entites_exterieur_V5
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "NomDuReseauWiFi"
  password: "MotDePasseWiFi"

# Déclaration des entités
binary_sensor:
  - platform: gpio
    pin: GPIO_NUM_1
    name: "Entite1"
  - platform: gpio
    pin: GPIO_NUM_2
    name: "Entite2"

# Déclaration des relais
switch:
  - platform: gpio
    pin: GPIO_NUM_4
    name: "Relais1"
  - platform: gpio
    pin: GPIO_NUM_5
    name: "Relais2"
  - platform: gpio
    pin: GPIO_NUM_6
    name: "Relais3"
  - platform: gpio
    pin: GPIO_NUM_7
    name: "Relais4"
  - platform: gpio
    pin: GPIO_NUM_8
    name: "Relais5"

# Automatisation pour allumer ou éteindre les relais en fonction des états des entités
automation:
  - alias: "Contrôle des relais"
    trigger:
      - platform: state
        entity_id: binary_sensor.entite1
      - platform: state
        entity_id: binary_sensor.entite2
    action:
      - choose:

      # Eteindre les relais en fonction des états des entités

          - conditions: # Entite1 OFF, Entite2 OFF
              - condition: state
                entity_id: binary_sensor.entite1
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "off"
            sequence:
              - switch.turn_off:
                  - relay1
                  - relay2
                  - relay3
                  - relay4
                  - relay5

      # Allumer les relais en fonction des états des entités

          - conditions: # Entite1 ON, Entite2 ON
              - condition: state
                entity_id: binary_sensor.entite1
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "on"
            sequence:
              - switch.turn_on:
                  - relay1
                  - relay2
                  - relay3
                  - relay4
                  - relay5
         

      # Allumer ou éteindre relay1, relay2, relay3, relay4 et relay5 en fonction des états des entités

          - conditions: # Entite1 ON, Entite3 OFF
              - condition: state
                entity_id: binary_sensor.entite1
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "off"
            sequence:
              - switch.turn_on:
                  - relay1
                  - relay2
                  - relay3
                  - relay4
              - switch.turn_off:
                  - relay5
          - conditions: # Entite1 OFF, Entite2 ON
              - condition: state
                entity_id: binary_sensor.entite1
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "on"
            sequence:
              - switch.turn_on:
                  - relay1
                  - relay2
                  - relay3
              - switch.turn_off:
                  - relay4
                  - relay5