esphome: # Déclaration du nom de l'ESP et de la carte utilisée
  name: esp_multi_relais_entites_exterieur_V5 # Nom de l'ESP
  platform: ESP8266 # Plateforme utilisée
  board: nodemcuv2 # Type de carte utilisée, ici une NodeMCU v2

wifi: # Configuration du WiFi, à adapter en fonction de votre réseau
  ssid: "NomDuReseauWiFi" # Nom du réseau WiFi
  password: "MotDePasseWiFi" # Mot de passe du réseau WiFi

# Déclaration des entités
binary_sensor: 
  - platform: gpio # Déclaration de la première entité
    pin: GPIO_NUM_1 # Broche GPIO à laquelle est connectée l'entité
    name: "Entite1" # Nom de l'entité
  - platform: gpio
    pin: GPIO_NUM_2
    name: "Entite2"
  - platform: gpio
    pin: GPIO_NUM_3
    name: "Entite3"

# Déclaration des relais
switch:
  - platform: gpio # Déclaration du premier relais
    pin: GPIO_NUM_4 # Broche GPIO à laquelle est connecté le relais
    name: "Relais1" # Nom du relais
  - platform: gpio
    pin: GPIO_NUM_5
    name: "Relais2"
  - platform: gpio
    pin: GPIO_NUM_6
    name: "Relais3"
  - platform: gpio
    pin: GPIO_NUM_7
    name: "Relais4"
  - platform: gpio
    pin: GPIO_NUM_8
    name: "Relais5"

# Automatisation pour allumer ou éteindre les relais en fonction des états des entités
automation:
  - alias: "Contrôle des relais" # Nom de l'automatisation
    trigger: # Déclencheurs de l'automatisation
      - platform: state # Déclencheur pour l'entité 1
        entity_id: binary_sensor.entite1 # Entité 1
      - platform: state
        entity_id: binary_sensor.entite2
      - platform: state
        entity_id: binary_sensor.entite3
    action:
      - choose:

      # Eteindre les relais en fonction des états des entités

          - conditions: # Entite1 OFF, Entite2 OFF, Entite3 OFF
              - condition: state
                entity_id: binary_sensor.entite1
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "off"
            sequence:
              - switch.turn_off:
                  - relay1
                  - relay2
                  - relay3
                  - relay4
                  - relay5

      # Allumer les relais en fonction des états des entités

          - conditions: # Entite1 ON, Entite2 ON, Entite3 ON
              - condition: state
                entity_id: binary_sensor.entite1
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "on"
            sequence:
              - switch.turn_on:
                  - relay1
                  - relay2
                  - relay3
                  - relay4
                  - relay5
         

      # Allumer ou éteindre relay1, relay2, relay3, relay4 et relay5 en fonction des états des entités

          - conditions: # Entite1 ON, Entite2 ON, Entite3 OFF
              - condition: state
                entity_id: binary_sensor.entite1
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "on"
            sequence:
              - switch.turn_on:
                  - relay1
                  - relay2
                  - relay3
                  - relay4
              - switch.turn_off:
                  - relay5
          - conditions: # Entite1 ON, Entite2 OFF, Entite3 OFF
              - condition: state
                entity_id: binary_sensor.entite1
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "off"
            sequence:
              - switch.turn_on:
                  - relay1
                  - relay2
                  - relay3
              - switch.turn_off:
                  - relay4
                  - relay5
          - conditions: # Entite1 ON, Entite2 OFF, Entite3 ON
              - condition: state
                entity_id: binary_sensor.entite1
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "on"
            sequence:
              - switch.turn_on:
                  - relay1
                  - relay2
              - switch.turn_off:
                  - relay3
                  - relay4
                  - relay5
          - conditions: # Entite1 OFF, Entite2 ON, Entite3 ON
              - condition: state
                entity_id: binary_sensor.entite1
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "off"
            sequence:
              - switch.turn_on:
                  - relay1
              - switch.turn_off:
                  - relay2
                  - relay3
                  - relay4
                  - relay5
          - conditions: # Entite1 OFF, Entite2 OFF, Entite3 ON
              - condition: state
                entity_id: binary_sensor.entite1
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "on"
            sequence:
              - switch.turn_on:
                  - relay1
                  - relay5
              - switch.turn_off:
                  - relay2
                  - relay3
                  - relay4
          - conditions: # Entite1 OFF, Entite2 ON, Entite3 OFF
              - condition: state
                entity_id: binary_sensor.entite1
                state: "off"
              - condition: state
                entity_id: binary_sensor.entite2
                state: "on"
              - condition: state
                entity_id: binary_sensor.entite3
                state: "off"
            sequence:
              - switch.turn_on:
                  - relay1
                  - relay4
              - switch.turn_off:
                  - relay2
                  - relay3
                  - relay5


          